# Generated by Django 4.1.2 on 2022-12-22 10:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("delivery", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="delivery",
            name="done",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="delivery",
            name="datetime",
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
