# Generated by Django 4.1.2 on 2022-12-19 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0022_remove_productselectedattributes_attribute_and_more"),
        ("cart", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="cart", name="selected_attributes",),
        migrations.AddField(
            model_name="cart",
            name="selected_attributes",
            field=models.ManyToManyField(to="product.productattributevalues"),
        ),
    ]
