# Generated by Django 4.1.2 on 2023-01-08 12:08

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("blogcategories", "0001_initial"),
        ("blogtags", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="posts/%Y/%m/%d/%h-%i-%s")),
                ("content", models.TextField()),
                ("title", models.CharField(max_length=200)),
                ("date", models.DateTimeField(default=datetime.datetime.now)),
                ("views", models.IntegerField(default=0)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="blogcategories.blogcategory",
                    ),
                ),
                ("tags", models.ManyToManyField(to="blogtags.blogtag")),
            ],
        ),
    ]
