# Generated by Django 4.1.6 on 2023-05-23 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
        ('post', '0004_alter_post_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='postcontentitem',
            name='content',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='postcontentitem',
            name='images',
            field=models.ManyToManyField(to='images.image'),
        ),
        migrations.AddField(
            model_name='postcontentitem',
            name='type',
            field=models.CharField(choices=[('SUBTITLE', 'Subtitle'), ('TEXT', 'Text'), ('QUOTE', 'Quote'), ('LIST', 'List')], default=' ', max_length=20),
            preserve_default=False,
        ),
    ]
