# Generated by Django 4.1.6 on 2023-05-23 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_postcontentitem_content_postcontentitem_images_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostContentOptionList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='postcontentitem',
            name='images',
        ),
        migrations.AlterField(
            model_name='postcontentitem',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='postcontentitem',
            name='options',
            field=models.ManyToManyField(blank=True, null=True, to='post.postcontentoptionlist'),
        ),
    ]
