# Generated by Django 4.1.2 on 2022-12-21 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shipping", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shipping", name="phone", field=models.CharField(max_length=20),
        ),
    ]
