# Generated by Django 4.1.2 on 2022-12-17 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Currency",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("currency", models.CharField(max_length=10, unique=True)),
                ("image", models.ImageField(upload_to="currencies/%Y/%m/%d/%h-%i-%s")),
                ("symbol", models.CharField(max_length=5, unique=True)),
            ],
        ),
    ]
