# Generated by Django 4.1.2 on 2022-12-17 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("currencies", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="currency",
            options={"verbose_name": "Currency", "verbose_name_plural": "Currencies"},
        ),
        migrations.RemoveField(model_name="currency", name="image",),
    ]
