# Generated by Django 4.1.2 on 2023-01-11 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscription", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscription",
            name="fall_quite",
            field=models.BooleanField(default=False),
        ),
    ]
