# Generated by Django 4.1.2 on 2022-12-21 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("product", "0022_remove_productselectedattributes_attribute_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Look",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "products",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="product.product",
                    ),
                ),
            ],
        ),
    ]
