# Generated by Django 4.1.2 on 2022-12-21 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0022_remove_productselectedattributes_attribute_and_more"),
        ("wishlist", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="wishlist",
            name="selected_attributes",
            field=models.ManyToManyField(to="product.productattributevalues"),
        ),
    ]
