# Generated by Django 4.1.2 on 2023-01-11 10:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Store",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.CharField(max_length=250)),
                ("phone", models.CharField(max_length=15)),
                ("address", models.CharField(max_length=200)),
                ("city", models.CharField(max_length=150)),
                ("country", models.CharField(max_length=200)),
                ("postalcode", models.CharField(max_length=20)),
                ("work_from", models.TimeField(default=datetime.datetime.now)),
                ("work_till", models.TimeField(default=datetime.datetime.now)),
                ("image", models.ImageField(upload_to="stores/%Y/%m/%d")),
            ],
        ),
    ]
