# Generated by Django 4.1.2 on 2022-12-17 10:48

import datetime
from django.db import migrations, models
import django.db.models.deletion
import product.models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "art_no",
                    models.CharField(
                        default=product.models.articul_number,
                        editable=False,
                        max_length=9,
                    ),
                ),
                ("qty", models.IntegerField(default=0)),
                ("price", models.TextField()),
                ("image_1", models.ImageField(upload_to="products/%Y/%m/%d/%h-%i-%s")),
                (
                    "image_2",
                    models.ImageField(
                        blank=True, null=True, upload_to="products/%Y/%m/%d/%h-%i-%s"
                    ),
                ),
                (
                    "image_3",
                    models.ImageField(
                        blank=True, null=True, upload_to="products/%Y/%m/%d/%h-%i-%s"
                    ),
                ),
                (
                    "image_4",
                    models.ImageField(
                        blank=True, null=True, upload_to="products/%Y/%m/%d/%h-%i-%s"
                    ),
                ),
                (
                    "video",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="videos/%Y/%m/%d/%h-%i-%s",
                        verbose_name="",
                    ),
                ),
                ("sale", models.IntegerField(default=0)),
                ("rating", models.IntegerField(default=0)),
                ("views", models.IntegerField(default=0)),
                (
                    "date_added",
                    models.DateTimeField(
                        blank=True, default=datetime.datetime.now, editable=False
                    ),
                ),
                (
                    "date_updated",
                    models.DateTimeField(blank=True, default=datetime.datetime.now),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProductCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name="ProductsType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="ProductSubCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="product.productcategory",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProductDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("details", models.TextField(blank=True, null=True)),
                ("fabric", models.TextField(blank=True, null=True)),
                ("care", models.TextField(blank=True, null=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="product.product",
                    ),
                ),
                (
                    "type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="product.productstype",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="productcategory",
            name="type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="product.productstype"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="category",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="product.productcategory",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="subcategory",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="product.productsubcategory",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="type",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="product.productstype",
            ),
        ),
        migrations.CreateModel(
            name="LookComplete",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("product", models.ManyToManyField(to="product.product")),
            ],
        ),
    ]
