# Generated by Django 4.1.2 on 2022-12-17 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="lookcomplete", name="name",),
    ]
