# Generated by Django 4.1.2 on 2022-12-17 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0002_remove_lookcomplete_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="lookcomplete",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="complete/%Y/%m/%d/%h-%i-%s"
            ),
        ),
    ]
