# Generated by Django 4.1.2 on 2022-12-17 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("currencies", "0002_alter_currency_options_remove_currency_image"),
        ("product", "0003_lookcomplete_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductPrices",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=2)),
                (
                    "currency",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="currencies.currency",
                    ),
                ),
            ],
        ),
    ]
