# Generated by Django 4.1.2 on 2022-12-17 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0004_productprices"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productprices",
            name="amount",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
