# Generated by Django 4.1.2 on 2022-12-17 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0005_alter_productprices_amount"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="prices",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="product.productprices",
            ),
            preserve_default=False,
        ),
    ]
