# Generated by Django 4.1.2 on 2022-12-17 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0006_product_prices"),
    ]

    operations = [
        migrations.RemoveField(model_name="product", name="price",),
        migrations.RemoveField(model_name="product", name="prices",),
    ]
