# Generated by Django 4.1.2 on 2022-12-17 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0007_remove_product_price_remove_product_prices"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="price",
            field=models.ManyToManyField(to="product.productprices"),
        ),
    ]
