# Generated by Django 4.1.2 on 2022-12-17 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0009_rename_price_product_prices"),
    ]

    operations = [
        migrations.RemoveField(model_name="product", name="prices",),
        migrations.AddField(
            model_name="productprices",
            name="product",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="product.product",
            ),
        ),
    ]
