# Generated by Django 4.1.2 on 2022-12-17 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("currencies", "0002_alter_currency_options_remove_currency_image"),
        ("product", "0010_remove_product_prices_productprices_product"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productprices",
            name="currency",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="currencies.currency"
            ),
        ),
    ]
