# Generated by Django 4.1.2 on 2022-12-18 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0012_productreview"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productreview",
            name="rating",
            field=models.DecimalField(decimal_places=1, max_digits=3),
        ),
    ]
