# Generated by Django 4.1.2 on 2022-12-18 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0013_alter_productreview_rating"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="rating",
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name="product",
            name="views",
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
