# Generated by Django 4.1.2 on 2022-12-18 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0015_productattribute_productattributevalues"),
    ]

    operations = [
        migrations.AddField(
            model_name="productattributevalues",
            name="displayValue",
            field=models.CharField(default="some", max_length=100),
            preserve_default=False,
        ),
    ]
