# Generated by Django 4.1.2 on 2022-12-18 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0016_productattributevalues_displayvalue"),
    ]

    operations = [
        migrations.AddField(
            model_name="productattributevalues",
            name="qty",
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name="ProductSelectedAttributes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "attribute",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="product.productattribute",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="product.product",
                    ),
                ),
                ("values", models.ManyToManyField(to="product.productattributevalues")),
            ],
        ),
    ]
