# Generated by Django 4.1.2 on 2022-12-18 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0020_product_brand"),
    ]

    operations = [
        migrations.RemoveField(model_name="productselectedattributes", name="values",),
        migrations.AddField(
            model_name="productselectedattributes",
            name="values",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="product.productattributevalues",
            ),
            preserve_default=False,
        ),
    ]
