# Generated by Django 4.1.2 on 2022-12-18 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0021_remove_productselectedattributes_values_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="productselectedattributes", name="attribute",
        ),
        migrations.RemoveField(model_name="productselectedattributes", name="values",),
        migrations.AddField(
            model_name="productselectedattributes",
            name="attribute",
            field=models.ManyToManyField(to="product.productattribute"),
        ),
        migrations.AddField(
            model_name="productselectedattributes",
            name="values",
            field=models.ManyToManyField(to="product.productattributevalues"),
        ),
    ]
