# Generated by Django 4.1.2 on 2023-01-12 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0022_remove_productselectedattributes_attribute_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="productcategory", name="type",),
    ]
