# Generated by Django 4.1.2 on 2023-01-12 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0025_alter_product_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="productcategory",
            name="type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="product.productstype",
            ),
        ),
    ]
