# Generated by Django 4.1.2 on 2023-01-14 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0026_productcategory_type"),
    ]

    operations = [
        migrations.RemoveField(model_name="productselectedattributes", name="qty",),
    ]
