# Generated by Django 4.1.6 on 2023-03-08 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0027_remove_productselectedattributes_qty'),
    ]

    operations = [
        migrations.AddField(
            model_name='productselectedattributes',
            name='qty',
            field=models.IntegerField(default=0),
        ),
    ]
