# Generated by Django 4.1.6 on 2023-03-08 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0028_productselectedattributes_qty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productselectedattributes',
            name='qty',
        ),
    ]
