# Generated by Django 4.1.6 on 2023-03-21 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
        ('product', '0029_remove_productselectedattributes_qty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image_1',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image_2',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image_3',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image_4',
        ),
        migrations.AddField(
            model_name='product',
            name='images',
            field=models.ManyToManyField(to='images.image'),
        ),
    ]
