# Generated by Django 4.1.2 on 2023-01-22 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=30)),
                ('twitter', models.CharField(max_length=100)),
                ('whatsapp', models.CharField(max_length=100)),
            ],
        ),
    ]
